#!/bin/bash
date

testup(){
    ping -c 1 -t 2 "$ip" > /dev/null
    if [ $? -eq 0 ]; then
    echo "$ip is up" 
    else
    echo "$ip is down"
    fi
}

if [ $# == 0 ]; then
while read -r line; do
  echo $line
done
exit 0
fi

for ip in $@
do
   testup $ip | grep up &
done
wait $(jobs -rp)
